### ISSUE TITLE
Gebruik classList-property en toggle i.p.v. className

### ISSUE THREAD

**Issue by vbrh-immalle** [WoutP-immalle/woutp-immalle.github.io#2]

**Comment by WoutP-immalle** [comment]
x.className veranderd de naam van de list in responsive, als het scherm klein is zoals op een smartphone, en verwijderd de naam 'responsive' weer op een groot scherm. Wanneer ik classList gebruik, werkt dit niet meer, aangezien ik de naam wil veranderen van de list.

**Comment by vbrh-immalle** [comment]
Dit stukje code:

```
function toggleMenu() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
            x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}
```

moet toch te refactoren zijn als een functie die van `classList` gebruik maakt, zou ik denken?
